---
-
   name: configuração da camada de configuracao apache 
   hosts: all 

 

   - name: reseta configuracao de rede 
     template:
         src: templates/httpd.j2
         dest: /etc/httpd/conf/httpd.conf
   
   - name: enable e inicia servico 
     systemd: 
         name: httpd 
         state: started
         enabled: yes 
