---
-
   name: configuração da camada de configuracao apache 
   hosts: all 
   tasks: 

 

      - name: seta configuracao do apache 
        template:
         src: templates/index.html.j2
         dest: /var/www/html/index.html


      - name: seta configuracao do apache 
        template:
         src: templates/httpd.conf.j2
         dest: /etc/httpd/conf/httpd.conf
        notify: 
          - reload-service
      
   handlers: 

      - name: reload-service 
        systemd: 
         name: httpd 
         state: reloaded
         enabled: yes 
