---
-
   name: Create virtual machine basic 
   hosts: localhost 
   vars: 

   tasks: 

   - name: Create a virtual machine from a template
     vmware_guest:
        datacenter: "DTC01"
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: /ansiblevms
        state: present
        guest_id: "rhel7_64Guest"
        name: "teste-debug.labs.corp"
        template: "t-rhel78"

        
    # This is hostname of particular ESXi server on which user wants VM to be deployed
        esxi_hostname: esx01.labs.corp
        disk:
        - size_gb: 15
          type: thin
          datastore: datastore1
        hardware:
          memory_mb: 512
          num_cpus: 2
          scsi: paravirtual
        networks:
        - name: "VM Network"
          #mac: aa:bb:dd:aa:00:14
          ip: "192.168.0.52"
          netmask: "255.255.255.0"
          device_type: "vmxnet3"
          start_connected: yes
          wake_on_lan: yes
        wait_for_ip_address: yes
     delegate_to: "localhost"
     register: "deploy_vm"   

   - name: Debug 
     debug: 
        msg: 
        - Saida dos deployment  '{{ deploy_vm }}'  

   - name: debug info + leitura via loop 
     debug: 
        msg: 
        - saida1 '{{item.hw_name}}'
        - saida2 '{{item.ipv4}}' 
     with_items:
        - "{{ deploy_vm.instance }}" 

   - name: leitura de variavel direta - 1 ok
     debug: 
        msg: 
        - saida1 direta  "{{deploy_vm.instance.hw_name}}" 
     ignore_errors: true 

   - name: leitura de variavel direta - 2
     debug: 
        msg: 
        - saida2 direta  "{{deploy_vm.hw_name}}" 
     ignore_errors: true 


   - name: set stats 
     set_stats: 
       data: 
        2_nome_da_vm: "{{deploy_vm.instance.hw_name}}" 
        per_host: yes 
     register: 2_nome_da_vm

   - name: debug-2 
     debug: 
        msg: 
        - saida especial teste "{{ 2_nome_da_vm }}"
     
#
#  - name: Add new instance to host group
#    add_host: hostname={{ item.public_ip }} groupname=launched
#    with_items: "{{ ec2.instances }}"

#  - name: Wait for SSH to come up
#    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
#    with_items: "{{ ec2.instances }}"
    
#  - name: Set variable for instance IP
#    set_fact:
#      instance_ip: "{{ item.public_ip }}"
#    with_items: "{{ ec2.instances }}"      

# openvm tools instalado 
# perl instalado 
# versao do rhel 7.8 atualziada nao ultima sub release
# vsphsre 6.7 
# parametros passado STRING 