---
-
   name: Create virtual machine basic 
   hosts: localhost 
   vars: 

   tasks: 

   - name: Create a virtual machine from a template
     vmware_guest:
        datacenter: DTC01
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: /ansiblevms
        state: poweredon
        guest_id: rhel7_64Guest
        name: gorda.labs.corp
        template: t-rhel7-v03-vmtools

        
    # This is hostname of particular ESXi server on which user wants VM to be deployed
        esxi_hostname: esx01.labs.corp
        disk:
        - size_gb: 15
          type: thin
          datastore: datastore1
        hardware:
          memory_mb: 512
          num_cpus: 2
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: aa:bb:dd:aa:00:14
          ip: 192.168.0.51
          netmask: 255.255.255.0
          device_type: vmxnet3
        wait_for_ip_address: yes
     delegate_to: localhost
     register: deploy_vm      