---
-
   name: Registra RHSM  
   hosts: all 
   vars: 
      user_nome: brolivei@redhat.com
      user_senha: RedBoo%10x
   tasks: 

     - name: Registro usando usuario e senha no RHSM 
       redhat_subscription:
          state: present
          username: "{{ user_nome }}"
          password: "{{ user_senha }}"
          auto_attach: true
          pool_ids:
            - 8a85f98260c27fc50160c32cc4365ccb 

     

     - name: Disable all RHSM repositories
       rhsm_repository:
         name: '*'
         state: disabled
       ignore_errors: true

     - name: Enable repository rhel-7-server-rpms
       rhsm_repository:
         name: rhel-7-server-rpms
      

     
