---
-
   name: WorkFlow - Registra RHSM  
   hosts: all 
   vars: 
      #user_nome: brolivei@redhat.com
      #user_senha: 
   tasks: 

    - name: Add new instance to host group
      yum: 
        name:  "{{pacote}}"
        state: latest
 
         

 #   - name: Wait for SSH to come up
 #     wait_for: host={{ item.ipv4 }} port=22 delay=60 timeout=320 state=started
 #     with_items: "{{ vmware_instances }}"
      
 #   - name: Installing and Configuring Ticket Monster Java App
 #     hosts: linux_launched
 #     gather_facts: True
 #     become: yes
 #     become_method: sudo 
  
