---
-
   name: Teste de conexão  
   hosts: localhost 
   tasks: 

     - name: Connect to website using a previously stored cookie   
       uri:
        url: "{{ v_servidor_teste }}"
        method: GET
        return_content: yes
        register: _result
          